-- AlterEnum
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'REJECTED';

-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "customerName" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "customerEmail" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "customerPhone" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "street" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "township" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "zipCode" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryMethodId" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryFee" DECIMAL(10,2);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paymentReference" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paymentProofUrl" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paymentProofUploadedAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "manualPaymentReviewedAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "manualPaymentReviewedBy" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "manualPaymentRejectionReason" TEXT;
